### ISSUE TITLE
Added default nginx files (removes?) the previous ones

### ISSUE THREAD

**Issue by sroze** [continuouspipe/dockerfiles#102]
Using the Symfony/php-fpm/nginx base image, when I add a file in `/etc/nginx/sites-available` named `default-10-xxx` it won't copy the "default default files", is it expected?

Used:
```
COPY ./docker/etc/ /etc
```

**Comment by kierenevans** [comment]
If a template from /etc/confd/ is going to write to /etc/nginx/sites-available/default-10-xxx, your changed file will be overwritten.

If you wish to change a file that comes from a template, you will need to overwrite the template file in /etc/confd/templates/ instead.

If no templates got written out, ensure you called `container start_supervisord` as your CMD in the Dockerfile (this is by default, unless you've overridden it). If needing a custom CMD, ensure you call `container confd` before starting services to get your templates written out.
