### ISSUE TITLE
Add `make` in the base images

### ISSUE THREAD

**Issue by sroze** [continuouspipe/dockerfiles#122]

**Comment by andytson-inviqa** [comment]
why?

**Comment by sroze** [comment]
So the users can still run their existing `Makefile` scripts without having to copy/paste the commands. If they are using the `make` things somewhere else, it makes sense to not ask them to duplicate the commands.

**Comment by kierenevans** [comment]
Make will be needed for Symfony 4: https://medium.com/@fabpot/symfony-4-best-practices-b4bbd6a9c994

**Comment by sroze** [comment]
^ yup, and I'm hitting the problem now :)

**Comment by andytson** [comment]
one thing I dislike about it is that it doesn't have a library way of providing make tasks. Therefore all our projects copy and paste in, which is exactly what Hem and the base image `plan.sh` was there to solve by allowing custom and shared tasks

**Comment by andytson-inviqa** [comment]
closed by #254
