### ISSUE TITLE
[Magento2] The `install_magento_custom.sh` script is called at runtime

### ISSUE THREAD

**Issue by sroze** [continuouspipe/dockerfiles#124]
This is the the `dev` tag (as of right now) of the M2 base image.

**Comment by andytson-inviqa** [comment]
Only when DEVELOPMENT_MODE is on tho right?

**Comment by kierenevans** [comment]
This is resolved by #95.

**Comment by kierenevans** [comment]
#95 got split into little PRs but this should be resolved in the `:latest` magento2 images now!
