### ISSUE TITLE
Failed supervisord services do not quit the container

### ISSUE THREAD

**Issue by sroze** [continuouspipe/dockerfiles#141]
When a supervisor program fail too many times, it won't be restarted by supervisord, but supervisor won't fail. Therefore the program is not running but the container orchestrator do not see the container as quitted and therefore can consider it as healthy...

We need to have supervisor failing in such scenario.

**Comment by kierenevans** [comment]
This is fixed by #210

**Comment by kierenevans** [comment]
and.... merged!
