### ISSUE TITLE
[Spryker] rename sites-available/default => sites-available/yves

### ISSUE THREAD

**Issue by dantleech** [continuouspipe/dockerfiles#369]
Rename `sites-available/default` to `sites-available/yves`.

- Remove the `default-01-webroot` file (put the webroot in `yves`)
- `zed` configuration can then include `default-*` instead of separately including all of the default configs.

**Comment by andytson-inviqa** [comment]
this is already done

**Comment by andytson-inviqa** [comment]
https://github.com/continuouspipe/dockerfiles/pull/356

**Comment by andytson-inviqa** [comment]
sorry https://github.com/continuouspipe/dockerfiles/pull/336
