### ISSUE TITLE
APP_ENDPOINT for symfony is /index.php instead of /app.php

### ISSUE THREAD

**Issue by TerjeBr** [continuouspipe/dockerfiles#405]
PR #394  has broken our build!

/usr/local/share/40-stack has this line:
export APP_ENDPOINT=${APP_ENDPOINT:-/index.php}

Before DEFAULT_APP_ENDPOINT was computed and used to set APP_ENDPOINT to /app.php
in /usr/local/share/env/30-framework
This logic with DEFAULT_APP_ENDPOINT has been moved to /usr/local/share/env/45-framework, but that runs after /usr/local/share/40-stack, so the APP_ENDPOINT now always ends up as /index.php.

**Comment by kierenevans** [comment]
Hi @TerjeBr, sorry that you encountered this.

Does using the stable tag instead of latest work for you?

Which symfony image variant are you using?

Do you have `symfony/flex` in your composer.lock anywhere?

**Comment by TerjeBr** [comment]
Our Dockerfile begins with
`FROM quay.io/continuouspipe/symfony-php7.1-apache:latest`

We were using latest instead of stable because of some other issues. But may be we can go back to stable, I will have to check.

No, `symfony/flex` is not in our composer.lock anywhere.

**Comment by TerjeBr** [comment]
This issue can now be closed, since #408 has been merged.

**Comment by kierenevans** [comment]
Thanks @TerjeBr!
